name: CI 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - run: "rustup component add clippy"
    - run: "sudo apt-get install wine"
    - run: "git clone --depth=1 https://github.com/est31/msvc-wine-rust.git"
    - uses: actions/checkout@v2
    - run: "cargo build --verbose"
    - run: "cargo test --verbose --tests"
    - run: "cargo test --verbose --doc"
    - run: "cargo doc --verbose"
    - run: "cargo build --verbose --release"
    - run: "cargo outdated --verbose --aggresssive --root-deps-only --exit-code 1"
    - run: "cargo clippy --verbose"
